stages:
  - build
  - deploy

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker-compose build
    - docker-compose push
  only:
    - main

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H 13.49.0.17 >> ~/.ssh/known_hosts
  script:
    - ssh ubuntu@13.49.0.17 'docker-compose -f ~/eco-budget/docker-compose.yml down'
    - scp docker-compose.yml ubuntu@13.49.0.17:~/eco-budget/docker-compose.yml
    - ssh ubuntu@13.49.0.17 'docker-compose -f ~/eco-budget/docker-compose.yml up -d'
  only:
    - main