stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker login git.cs.bham.ac.uk:5050 -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    - docker build --platform linux/amd64 -t git.cs.bham.ac.uk:5050/txa139/eco-budget/eco-budget-frontend ./frontend
    - docker build --platform linux/amd64 -t git.cs.bham.ac.uk:5050/txa139/eco-budget/eco-budget-backend ./eco_budget
    - docker push git.cs.bham.ac.uk:5050/txa139/eco-budget/eco-budget-frontend
    - docker push git.cs.bham.ac.uk:5050/txa139/eco-budget/eco-budget-backend

deploy:
  stage: deploy
  script:
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh -vvv -o StrictHostKeyChecking=no ubuntu@$EC2_PUBLIC_IP "cd ~/eco-budget && ./deploy.sh"